services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: store_plants
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/store_plants?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
      # Para JWT si lo usas por env:
      # SECURITY_JWT_SECRET: super-secreto-cambia-esto
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Se inyecta en el build de Vite (usado en import.meta.env.VITE_API_BASE_URL)
        VITE_API_BASE_URL: http://localhost:8080
    environment:
      # Por si en tiempo de build quieres usarla también como ENV
      VITE_API_BASE_URL: http://localhost:8080
    depends_on:
      - backend
    ports:
      - "5173:80"
    # Si sirves assets estáticos, no necesitas volumes aquí

volumes:
  mysql_data:
